# Generated by Django 6.0.5 on 2026-05-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='provider_service_id',
            field=models.CharField(max_length=255),
        ),
    ]
