# Generated by Django 6.0.5 on 2026-05-24 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_transaction_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='texttospeechrequest',
            name='updated_at',
        ),
    ]
