# Generated by Django 6.0.5 on 2026-05-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_texttospeechrequest_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='target_link',
            field=models.URLField(max_length=1000),
        ),
    ]
