# Generated by Django 6.0.5 on 2026-05-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaaccount',
            name='link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
