# Generated by Django 6.0.5 on 2026-05-27 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_socialmediaaccount_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='description',
        ),
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='price',
        ),
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='user',
        ),
        migrations.AlterField(
            model_name='socialmediaaccount',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.platform'),
        ),
    ]
