# Generated by Django 6.0.5 on 2026-05-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_platform_remove_socialmediaaccount_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
