# Generated by Django 6.0.5 on 2026-05-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_accountorder_user_userplatformaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaaccount',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
