# Generated by Django 6.0.5 on 2026-05-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_transaction_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='access_pswd',
        ),
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='username',
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='logs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
