# Generated by Django 6.0.5 on 2026-06-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_socialmediaaccount_access_pswd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='platform_icons/'),
        ),
    ]
