# Generated by Django 6.0.5 on 2026-06-09 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_mysmvaultproduct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mysmvaultproduct',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='smvault_products', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
