# Generated by Django 6.0.5 on 2026-06-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_mysmvaultproduct_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysmvaultproduct',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
