# Generated by Django 6.0.5 on 2026-05-28 07:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_receivedemail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receivedemail',
            options={'ordering': ['-received_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='receivedemail',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='receivedemail',
            name='bcc',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='receivedemail',
            name='cc',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='receivedemail',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='receivedemail',
            name='email_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='receivedemail',
            name='message_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receivedemail',
            name='recipients',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='receivedemail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='receivedemail',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='receivedemail',
            name='received_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='receivedemail',
            name='subject',
            field=models.CharField(blank=True, default='(No subject)', max_length=255),
        ),
    ]
